import React from "react"
import { Box, Flex, Link as Link2, useColorModeValue } from "@chakra-ui/react"
import ColorSwitcher from "../ColorSwitcher"
import SearchInput from "../SearchInput"
import { Link } from "react-router-dom"
